version: '3'
services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment: 
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    volumes:
      - ./app:/src
    ports:
      - 3000:3000
  redis:
    image: redis
  static:
    build:
      context: ./static
      dockerfile: Dockerfile
    volumes:
      - ./static:/usr/share/nginx/html