version: '3'
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - static
      - app
    ports:
      - "80:80"
    restart: always
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment: 
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    volumes:
      - ./app:/src
  redis:
    image: redis
  static:
    build:
      context: ./static
      dockerfile: Dockerfile
    volumes:
      - ./static:/usr/share/nginx/html